//! The typed AST produced by the parser and consumed by the protocol layer.
//!
//! These types model the GDB/MI v3 output grammar as documented in the GDB
//! manual. Each type corresponds directly to a BNF production:
//!
//! ```text
//! output               → (out-of-band-record)* [result-record] "(gdb)" nl
//! result-record        → [token] "^" result-class ("," result)* nl
//! *|+|=-async-output   → [token] "*|+|=" async-class ("," result)* nl
//! stream-output        → ("~"|"@"|"&") c-string nl
//! result               → variable "=" value
//! value                → const | tuple | list
//! ```
//!
//! Design choices baked into these types (see `wild-tickling-torvalds.md`):
//!
//! - **`AsyncClass` is a newtype over `String`, not an enum.** GDB adds new
//!   async classes with every release (e.g. `=record-started`,
//!   `=tsv-modified`); a closed enum would reject unknown classes and break
//!   every frontend on the next GDB upgrade.
//! - **`ResultClass` *is* an enum.** The BNF fixes it at exactly five values.
//! - **Result tuples are `Vec<(String, Value)>`, not `HashMap`.** MI
//!   preserves key order and is permitted to emit duplicate keys; map types
//!   lose both.
//! - **`Value::Const` is `String`, fail-closed on invalid UTF-8.** GDB emits
//!   UTF-8 in practice; modelling consts as `Vec<u8>` would poison every
//!   downstream consumer with lossy conversions. Invalid UTF-8 becomes a
//!   hard parse error.

use alloc::string::String;
use alloc::vec::Vec;
use core::fmt;

/// A numeric token echoed by GDB on the record produced in response to a
/// tokenised command. Tokens are chosen by the frontend on the way in and
/// appear as the prefix `123-exec-run`; GDB echoes them on the result and
/// async records generated by that command.
///
/// framewalk represents tokens as `u64`; the BNF allows arbitrary digit
/// sequences in principle, but 20 decimal digits is more than any frontend
/// will ever want. Token values that exceed `u64::MAX` are a hard parse
/// error ([`CodecErrorKind::TokenOverflow`](crate::error::CodecErrorKind::TokenOverflow)).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Token(pub u64);

impl Token {
    #[inline]
    #[must_use]
    pub const fn new(n: u64) -> Self {
        Self(n)
    }

    #[inline]
    #[must_use]
    pub const fn get(self) -> u64 {
        self.0
    }
}

impl From<u64> for Token {
    #[inline]
    fn from(n: u64) -> Self {
        Self(n)
    }
}

impl fmt::Display for Token {
    #[inline]
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

/// A complete parsed MI output record, corresponding to one non-terminator
/// line emitted by GDB.
///
/// The seven variants cover the seven record forms in the BNF: a single
/// result record, three kinds of async record (exec `*`, status `+`, notify
/// `=`), and three kinds of stream record (console `~`, target `@`,
/// log `&`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Record {
    /// `[token] "^" result-class ("," result)*`
    Result(ResultRecord),
    /// `[token] "*" async-class ("," result)*` — target execution state
    /// change (typically `*stopped` / `*running`).
    Exec(AsyncRecord),
    /// `[token] "+" async-class ("," result)*` — status update (rarely
    /// emitted by modern GDB, kept for completeness).
    Status(AsyncRecord),
    /// `[token] "=" async-class ("," result)*` — notification (thread
    /// created, library loaded, breakpoint modified, etc).
    Notify(AsyncRecord),
    /// `"~" c-string` — console stream output meant for display.
    Console(StreamRecord),
    /// `"@" c-string` — target program's own stdout (remote targets only).
    Target(StreamRecord),
    /// `"&" c-string` — GDB internal log output.
    Log(StreamRecord),
}

/// A result record: `^done`, `^running`, `^connected`, `^error`, or `^exit`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResultRecord {
    pub token: Option<Token>,
    pub class: ResultClass,
    /// Ordered key-value results following the class. Keys may be duplicated
    /// (MI does not forbid it) so a `Vec` is used instead of a map type.
    pub results: Vec<(String, Value)>,
}

/// An async record: `*<class>`, `+<class>`, or `=<class>`. The record's
/// *kind* (exec / status / notify) is carried by the enclosing
/// [`Record`] variant; this struct holds the parts shared by all three.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AsyncRecord {
    pub token: Option<Token>,
    pub class: AsyncClass,
    /// Ordered key-value results following the class (same semantics as
    /// [`ResultRecord::results`]).
    pub results: Vec<(String, Value)>,
}

/// A stream record: `~"..."`, `@"..."`, or `&"..."`. The enclosing [`Record`]
/// variant carries the channel (Console / Target / Log); this struct holds
/// the decoded payload.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StreamRecord {
    /// The c-string payload, with escape sequences already decoded. A
    /// `\n` in the wire becomes a real newline in this string; callers
    /// never see the escape form.
    pub text: String,
}

/// The five result classes the BNF fixes for result records.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ResultClass {
    /// `^done` — synchronous command completed successfully.
    Done,
    /// `^running` — command accepted; target is now running.
    ///
    /// This is a *completion* from the protocol's perspective — the caller
    /// should not keep the command pending waiting for a `*stopped`. See
    /// the "`^running` is a command completion, not a pending state" design
    /// decision in `wild-tickling-torvalds.md`.
    Running,
    /// `^connected` — GDB has connected to a remote target.
    Connected,
    /// `^error,msg=...[,code=...]` — command failed.
    Error,
    /// `^exit` — GDB is exiting.
    Exit,
}

impl ResultClass {
    /// Parse a result-class name from its byte spelling. Returns `None` if
    /// the name does not match any documented class.
    #[must_use]
    pub fn from_bytes(bytes: &[u8]) -> Option<Self> {
        match bytes {
            b"done" => Some(Self::Done),
            b"running" => Some(Self::Running),
            b"connected" => Some(Self::Connected),
            b"error" => Some(Self::Error),
            b"exit" => Some(Self::Exit),
            _ => None,
        }
    }

    /// The canonical byte spelling of this class.
    #[must_use]
    pub const fn as_bytes(self) -> &'static [u8] {
        match self {
            Self::Done => b"done",
            Self::Running => b"running",
            Self::Connected => b"connected",
            Self::Error => b"error",
            Self::Exit => b"exit",
        }
    }
}

/// An async class, stored as an owned string rather than an enum to allow
/// forward compatibility with GDB releases that introduce new classes.
///
/// Well-known classes include `stopped`, `running`, `thread-created`,
/// `thread-exited`, `breakpoint-created`, `breakpoint-modified`,
/// `breakpoint-deleted`, `library-loaded`, `library-unloaded`,
/// `thread-group-added`, `thread-group-started`, and many more. The parser
/// accepts anything syntactically valid (non-empty identifier characters);
/// it's the protocol layer's job to decide which classes it cares about.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AsyncClass(pub String);

impl AsyncClass {
    #[inline]
    #[must_use]
    pub fn new(name: impl Into<String>) -> Self {
        Self(name.into())
    }

    #[inline]
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for AsyncClass {
    #[inline]
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// An MI value: the right-hand side of a `result`.
///
/// The four variants correspond to the BNF productions `const`, `tuple`, and
/// the two shapes of `list`. An empty list (`[]`) is represented as
/// [`Value::List`] wrapping [`ListValue::Empty`]; callers that need to
/// distinguish empty from value-list-of-zero-elements can match on it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Value {
    /// A `const`: a c-string literal with escapes decoded.
    Const(String),
    /// A `tuple`: `{name=value,...}`. Keys may repeat; order is preserved.
    Tuple(Vec<(String, Value)>),
    /// A `list`: `[value,...]` (bare values) or `[name=value,...]` (results)
    /// or `[]` (empty).
    List(ListValue),
}

/// The three shapes a list production can take.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ListValue {
    /// `[]` — an empty list. framewalk does not infer a value-vs-result
    /// shape for empty lists; callers treat it as universally empty.
    Empty,
    /// `[v1,v2,v3]` — a list of bare values.
    Values(Vec<Value>),
    /// `[k1=v1,k2=v2]` — a list of key-value pairs.
    Results(Vec<(String, Value)>),
}
